[versions]
minecraft = "1.18.2-R0.1-SNAPSHOT"

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version = "1.18.26" }

# Testing
junitApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version = "5.8.2" }
junitEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version = "5.8.2" }
